{{- if and .Values.api.enabled (not .Values.api.license.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cypher-workbench.api.fullname" . }}-license
  labels:
    {{- include "cypher-workbench.api.labels" .  < /dev/null |  nindent 4 }}
type: Opaque
data:
  license.lic: {{ .Values.api.license.content | b64enc }}
{{- end }}
