{{- if and .Values.neo4j.enabled (not .Values.neo4j.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cypher-workbench.neo4j.fullname" . }}-auth
  labels:
    {{- include "cypher-workbench.neo4j.labels" .  < /dev/null |  nindent 4 }}
type: Opaque
data:
  neo4j-username: {{ .Values.neo4j.auth.username | b64enc }}
  neo4j-password: {{ .Values.neo4j.auth.password | b64enc }}
{{- end }}
