apiVersion: v2
name: cypher-workbench
description: A Helm chart for Cypher Workbench
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - neo4j
  - graph
  - cypher
  - workbench
maintainers:
  - name: Neo4j
    url: https://neo4j.com/
dependencies:
  - name: common
    version: ^1.0.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
  - name: neo4j
    version: ^5.5.0
    repository: https://helm.neo4j.com/neo4j
    condition: neo4j.enabled