server {
    listen 80;
    server_name localhost neo4j.visionquest.space;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name localhost neo4j.visionquest.space;

    ssl_certificate     /etc/ssl/server.crt;
    ssl_certificate_key /etc/ssl/server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri /index.html;
    }

    location /graphql {
        proxy_pass http://cypher-workbench-api:4000/graphql;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    location /neo4jbrowser/ {
        proxy_pass         http://host.docker.internal:7474/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;

        # Rewrite backend redirects (/… → /neo4jbrowser/…)
        proxy_redirect     ~^(/.*)$ /neo4jbrowser$1;

        # Rewrite HTML/JS asset paths
        sub_filter_types   text/html text/css application/javascript;
        sub_filter         'href="/browser' 'href="/neo4jbrowser/browser';
        sub_filter         'src="/browser'  'src="/neo4jbrowser/browser';
        sub_filter_once    off;
    }

    location /api/ {
        proxy_pass         http://host.docker.internal:81/api/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }


    location ~ ^/vq-graphql(.*)$ {
        rewrite ^/vq-graphql(.*)$ /graphql$1 break;
        proxy_pass         http://host.docker.internal:4001;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Content-Type $content_type;
        proxy_pass_request_headers on;
        proxy_pass_request_body on;
    }

    #location /graphql {
    #    proxy_pass http://${GRAPHQL_HOST}:${GRAPHQL_PORT}/graphql;
    #}
 
    # EM: see article here for more info:
    # https://serverfault.com/questions/577370/how-can-i-use-environment-variables-in-nginx-conf

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
